import type { Metadata } from "next";
import "./globals.css";
import { generalSans, tanker } from "@/fonts/fonts";
import Navbar from "@/components/Navbar";
import Container from "@/components/Container";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Develog - Kaif's Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${generalSans.className} ${tanker.variable} antialiased bg-background text-foreground`}
      >
        <Navbar />
        <main className="w-full min-h-screen">
          <Container>{children}</Container>
        </main>
        <Footer />
      </body>
    </html>
  );
}
